export type SectionCard = {
  title: string;
  text: string;
  label?: string;
  tags?: string[];
  href?: string;
  external?: boolean;
};

export type SectionDefinition = {
  title: string;
  eyebrow: string;
  description: string;
  intro?: string;
  cards: SectionCard[];
  note?: string;
  primaryAction?: { label: string; href: string; external?: boolean };
  secondaryAction?: { label: string; href: string; external?: boolean };
};

export const sections: Record<string, SectionDefinition> = {
  about: {
    title: 'About Manarth Patel',
    eyebrow: 'Professional Profile',
    description:
      'Cyber Security Engineer with 5+ years of experience across security operations, backend development, technical support, and IT infrastructure.',
    intro:
      'Manarth’s background combines cybersecurity operations with infrastructure support and software-development experience, supporting a practical understanding of identities, endpoints, networks, applications, and backend systems.',
    cards: [
      {
        title: 'Security Operations',
        text: 'Security monitoring, alert triage, log analysis, incident investigation, IOC analysis, response support, and technical documentation.',
        label: 'Professional capability',
        tags: ['Monitoring', 'Investigation', 'Documentation']
      },
      {
        title: 'Identity and Access Management',
        text: 'Active Directory, Microsoft Entra ID, account lifecycle, MFA, authentication support, groups, permissions, access reviews, and least privilege.',
        label: 'Professional capability',
        tags: ['Active Directory', 'Entra ID', 'MFA']
      },
      {
        title: 'Vulnerability and Infrastructure Security',
        text: 'Vulnerability assessment, configuration reviews, remediation tracking, fix validation, system hardening, Windows and Linux environments, networking, and security-control validation.',
        label: 'Professional capability',
        tags: ['Vulnerability Management', 'Infrastructure', 'Hardening']
      },
      {
        title: 'Development and Technical Support',
        text: 'Python, FastAPI, REST APIs, MongoDB, API testing, Windows support, networking, troubleshooting, root-cause analysis, and technical documentation.',
        label: 'Technical foundation',
        tags: ['Python', 'FastAPI', 'Technical Support']
      }
    ],
    primaryAction: { label: 'View professional experience', href: '/resume/' },
    secondaryAction: { label: 'Explore projects', href: '/projects/' }
  },
  blog: {
    title: 'Cybersecurity Blog',
    eyebrow: 'Learning and Documentation',
    description:
      'Practical cybersecurity writing covering security operations, identity, vulnerability management, infrastructure, cloud security, and lessons from documented technical work.',
    intro:
      'Articles will be published when they contain useful explanation, practical guidance, and reviewed technical content.',
    cards: [],
    primaryAction: { label: 'Explore the lab programme', href: '/labs/' },
    secondaryAction: { label: 'View projects', href: '/projects/' }
  },
  glossary: {
    title: 'Cybersecurity Glossary',
    eyebrow: 'Plain-English Security',
    description:
      'Clear explanations of common cybersecurity terms for recruiters, learners, and technical visitors.',
    cards: [
      { title: 'Security Operations Centre (SOC)', text: 'A team that monitors security activity, investigates alerts, and coordinates response.', label: 'SOC' },
      { title: 'Security Information and Event Management (SIEM)', text: 'A platform that collects and analyzes logs so analysts can detect and investigate suspicious activity.', label: 'SIEM' },
      { title: 'Identity and Access Management (IAM)', text: 'The people, processes, and technology used to control who can access systems and data.', label: 'IAM' },
      { title: 'Multi-factor Authentication (MFA)', text: 'An additional verification step that reduces the chance of a stolen password being enough to sign in.', label: 'MFA' },
      { title: 'MITRE ATT&CK', text: 'A knowledge base used to describe adversary tactics and techniques.', label: 'ATT&CK' },
      { title: 'Zero Trust', text: 'A security model that verifies access continuously rather than trusting users or devices by default.', label: 'Zero Trust' },
      { title: 'Log', text: 'A record of activity generated by a system, application, user, or security tool.', label: 'Log' },
      { title: 'Alert', text: 'A notification that activity may require investigation. An alert is not automatically an incident.', label: 'Alert' },
      { title: 'Security Incident', text: 'An event or series of events that threatens confidentiality, integrity, or availability and requires response.', label: 'Incident' }
    ],
    primaryAction: { label: 'Read the blog', href: '/blog/' },
    secondaryAction: { label: 'Explore labs', href: '/labs/' }
  },
  resume: {
    title: 'Resume',
    eyebrow: 'Career Profile',
    description:
      'Professional experience, technical capabilities, education, and an ATS-friendly downloadable resume.',
    cards: [],
    primaryAction: { label: 'Open resume PDF', href: '/assets/docs/Manarth_Patel_Resume_IT_SOC.pdf', external: true },
    secondaryAction: { label: 'Contact Manarth', href: '/contact/' }
  },
  contact: {
    title: 'Contact Manarth Patel',
    eyebrow: 'Contact',
    description:
      'Connect regarding cybersecurity opportunities, professional networking, portfolio discussion, or technical collaboration.',
    cards: [
      { title: 'Email', text: 'manarthpatel108@outlook.com', label: 'Direct', href: 'mailto:manarthpatel108@outlook.com' },
      { title: 'LinkedIn', text: 'Professional profile, updates, and networking.', label: 'Professional', href: 'https://www.linkedin.com/in/manarthpatel/', external: true },
      { title: 'GitHub', text: 'Code, project repositories, and technical work.', label: 'Technical', href: 'https://github.com/PatelManarth', external: true },
      { title: 'Location', text: 'Greater Toronto Area, Ontario, Canada. Open to remote, hybrid, and onsite opportunities across Canada.', label: 'Canada' }
    ],
    primaryAction: { label: 'Email about a role', href: 'mailto:manarthpatel108@outlook.com?subject=Cybersecurity%20role%20opportunity' },
    secondaryAction: { label: 'Discuss the portfolio', href: 'mailto:manarthpatel108@outlook.com?subject=Portfolio%20discussion' }
  }
};
